In [1]:
import pandas as pd

In [42]:
data=pd.read_csv("nba.csv")
data

,Unnamed: 0,player_name,team_abbreviation,age,player_height,player_weight,college,country,draft_year,draft_round,...,pts,reb,ast,net_rating,oreb_pct,dreb_pct,usg_pct,ts_pct,ast_pct,season
0,0,Dennis Rodman,CHI,36.0,198.12,99.790240,Southeastern Oklahoma State,USA,1986,2,...,5.7,16.1,3.1,16.1,0.186,0.323,0.100,0.479,0.113,1996-97
1,1,Dwayne Schintzius,LAC,28.0,215.90,117.933920,Florida,USA,1990,1,...,2.3,1.5,0.3,12.3,0.078,0.151,0.175,0.430,0.048,1996-97
2,2,Earl Cureton,TOR,39.0,205.74,95.254320,Detroit Mercy,USA,1979,3,...,0.8,1.0,0.4,-2.1,0.105,0.102,0.103,0.376,0.148,1996-97
3,3,Ed O'Bannon,DAL,24.0,203.20,100.697424,UCLA,USA,1995,1,...,3.7,2.3,0.6,-8.7,0.060,0.149,0.167,0.399,0.077,1996-97
4,4,Ed Pinckney,MIA,34.0,205.74,108.862080,Villanova,USA,1985,1,...,2.4,2.4,0.2,-11.2,0.109,0.179,0.127,0.611,0.040,1996-97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11140,11140,Maxi Kleber,DAL,28.0,208.28,108.862080,None,Germany,Undrafted,Undrafted,...,9.1,5.4,1.1,4.6,0.056,0.140,0.136,0.605,0.064,2019-20
11141,11141,Melvin Frazier Jr.,ORL,23.0,195.58,97.522280,Tulane,USA,2018,2,...,1.2,0.3,0.1,-2.4,0.018,0.058,0.164,0.480,0.033,2019-20
11142,11142,Meyers Leonard,MIA,28.0,213.36,117.933920,Illinois,USA,2012,1,...,6.1,5.1,1.1,5.6,0.029,0.217,0.120,0.640,0.076,2019-20
11143,11143,Norvel Pelle,PHI,27.0,208.28,104.779752,None,USA,Undrafted,Undrafted,...,2.1,3.0,0.4,-16.4,0.085,0.237,0.126,0.521,0.056,2019-20
11144,11144,Matt Thomas,TOR,25.0,193.04,86.182480,Iowa State,USA,Undrafted,Undrafted,...,4.5,1.4,0.5,1.0,0.017,0.104,0.149,0.663,0.089,2019-20

In [79]:
data.groupby("team_abbreviation").get_group("MIN")[["player_name","pts"]].sort_values(by="pts",ascending=False)

              player_name   pts
11069  Karl-Anthony Towns  26.5
7974           Kevin Love  26.1
7026           Kevin Love  26.0
9186   Karl-Anthony Towns  25.1
10549  Karl-Anthony Towns  24.4
...                   ...   ...
9293       John Lucas III   0.4
7193          Will Conroy   0.3
5762          Mark Madsen   0.3
990         Trevor Winter   0.0
8467         Ronny Turiaf   0.0

[366 rows x 2 columns]

In [66]:
data["player_name"].unique()

array(['Dennis Rodman', 'Dwayne Schintzius', 'Earl Cureton', ...,
       'Max Strus', 'Norvel Pelle', 'Matt Thomas'], dtype=object)

In [80]:
data.groupby("team_abbreviation").get_group("MIN")["player_name"].value_counts()

Kevin Garnett        13
Anthony Peeler        6
Gorgui Dieng          6
Sam Mitchell          6
Wally Szczerbiak      6
                     ..
Will Conroy           1
AJ Price              1
DeJuan Wheat          1
Jordan McLaughlin     1
Allen Crabbe          1
Name: player_name, Length: 188, dtype: int64

In [81]:
data.head(10)

,Unnamed: 0,player_name,team_abbreviation,age,player_height,player_weight,college,country,draft_year,draft_round,...,pts,reb,ast,net_rating,oreb_pct,dreb_pct,usg_pct,ts_pct,ast_pct,season
0,0,Dennis Rodman,CHI,36.0,198.12,99.790240,Southeastern Oklahoma State,USA,1986,2,...,5.7,16.1,3.1,16.1,0.186,0.323,0.100,0.479,0.113,1996-97
1,1,Dwayne Schintzius,LAC,28.0,215.90,117.933920,Florida,USA,1990,1,...,2.3,1.5,0.3,12.3,0.078,0.151,0.175,0.430,0.048,1996-97
2,2,Earl Cureton,TOR,39.0,205.74,95.254320,Detroit Mercy,USA,1979,3,...,0.8,1.0,0.4,-2.1,0.105,0.102,0.103,0.376,0.148,1996-97
3,3,Ed O'Bannon,DAL,24.0,203.20,100.697424,UCLA,USA,1995,1,...,3.7,2.3,0.6,-8.7,0.060,0.149,0.167,0.399,0.077,1996-97
4,4,Ed Pinckney,MIA,34.0,205.74,108.862080,Villanova,USA,1985,1,...,2.4,2.4,0.2,-11.2,0.109,0.179,0.127,0.611,0.040,1996-97
5,5,Eddie Johnson,HOU,38.0,200.66,97.522280,Illinois,USA,1981,2,...,8.2,2.7,1.0,4.1,0.034,0.126,0.220,0.541,0.102,1996-97
6,6,Eddie Jones,LAL,25.0,198.12,86.182480,Temple,USA,1994,1,...,17.2,4.1,3.4,4.1,0.035,0.091,0.209,0.559,0.149,1996-97
7,7,Elden Campbell,LAL,28.0,213.36,113.398000,Clemson,USA,1990,1,...,14.9,8.0,1.6,3.3,0.095,0.183,0.222,0.520,0.087,1996-97
8,8,Eldridge Recasner,ATL,29.0,193.04,86.182480,Washington,USA,1992,Undrafted,...,5.7,1.6,1.3,-0.3,0.036,0.076,0.172,0.539,0.141,1996-97
9,9,Elliot Perry,MIL,28.0,182.88,72.574720,Memphis,USA,1991,2,...,6.9,1.5,3.0,-1.2,0.018,0.081,0.177,0.557,0.262,1996-97

In [88]:
data["age"].mean()

27.168685509196948

In [89]:
data["age"].max()

44.0

In [98]:
data[data["age"]==data["age"].max()]["player_name"]

4820    Kevin Willis
Name: player_name, dtype: object

In [105]:
data[data["player_name"]=="Kevin Garnett"].sort_values(ascending=False,by="pts")

,Unnamed: 0,player_name,team_abbreviation,age,player_height,player_weight,college,country,draft_year,draft_round,...,pts,reb,ast,net_rating,oreb_pct,dreb_pct,usg_pct,ts_pct,ast_pct,season
3134,3134,Kevin Garnett,MIN,28.0,210.82,108.862080,None,USA,1995,1,...,24.2,13.9,5.0,10.4,0.092,0.298,0.294,0.547,0.233,2003-04
3007,3007,Kevin Garnett,MIN,27.0,210.82,99.790240,None,USA,1995,1,...,23.0,13.4,6.0,6.8,0.086,0.282,0.262,0.553,0.249,2002-03
1698,1698,Kevin Garnett,MIN,24.0,210.82,99.790240,None,USA,1995,1,...,22.9,11.8,5.0,5.7,0.080,0.267,0.276,0.545,0.211,1999-00
4817,4817,Kevin Garnett,MIN,31.0,210.82,114.758776,None,USA,1995,1,...,22.4,12.8,4.1,-0.5,0.077,0.308,0.276,0.546,0.190,2006-07
3578,3578,Kevin Garnett,MIN,29.0,210.82,99.790240,None,USA,1995,1,...,22.2,13.5,5.7,1.2,0.095,0.303,0.269,0.567,0.264,2004-05
2084,2084,Kevin Garnett,MIN,25.0,210.82,99.790240,None,USA,1995,1,...,22.0,11.4,5.0,3.7,0.078,0.252,0.271,0.531,0.215,2000-01
4032,4032,Kevin Garnett,MIN,30.0,210.82,99.790240,None,USA,1995,1,...,21.8,12.7,4.1,0.8,0.092,0.296,0.256,0.589,0.194,2005-06
2254,2254,Kevin Garnett,MIN,26.0,210.82,99.790240,None,USA,1995,1,...,21.2,12.1,5.2,5.8,0.091,0.264,0.261,0.536,0.220,2001-02
1094,1094,Kevin Garnett,MIN,23.0,210.82,99.790240,None,USA,1995,1,...,20.8,10.4,4.3,2.3,0.097,0.219,0.278,0.493,0.206,1998-99
5163,5163,Kevin Garnett,BOS,32.0,210.82,99.790240,None,USA,1995,1,...,18.8,9.2,3.4,17.0,0.075,0.246,0.257,0.588,0.186,2007-08
543,543,Kevin Garnett,MIN,22.0,210.82,99.790240,None,USA,1995,1,...,18.5,9.6,4.2,2.5,0.080,0.197,0.225,0.527,0.178,1997-98
337,337,Kevin Garnett,MIN,21.0,210.82,99.790240,None,USA,1995,1,...,17.0,8.0,3.1,2.8,0.077,0.166,0.215,0.537,0.139,1996-97
5412,5412,Kevin Garnett,BOS,33.0,210.82,114.758776,None,USA,1995,1,...,15.8,8.5,2.5,14.9,0.057,0.255,0.234,0.563,0.137,2008-09
7025,7025,Kevin Garnett,BOS,36.0,210.82,114.758776,None,USA,1995,1,...,15.8,8.2,2.9,7.7,0.045,0.261,0.251,0.550,0.171,2011-12
6246,6246,Kevin Garnett,BOS,35.0,210.82,114.758776,None,USA,1995,1,...,14.9,8.9,2.4,13.1,0.049,0.277,0.221,0.575,0.127,2010-11
7458,7458,Kevin Garnett,BOS,37.0,210.82,114.758776,None,USA,1995,1,...,14.8,7.8,2.3,3.5,0.046,0.259,0.251,0.535,0.147,2012-13
6164,6164,Kevin Garnett,BOS,34.0,210.82,114.758776,None,USA,1995,1,...,14.3,7.3,2.7,8.1,0.049,0.236,0.220,0.569,0.148,2009-10
8339,8339,Kevin Garnett,MIN,39.0,210.82,114.758776,None,USA,1995,1,...,6.9,6.6,1.6,0.2,0.059,0.316,0.184,0.496,0.131,2014-15
7973,7973,Kevin Garnett,BKN,38.0,210.82,114.758776,None,USA,1995,1,...,6.5,6.6,1.5,-1.3,0.066,0.314,0.194,0.467,0.130,2013-14
8793,8793,Kevin Garnett,MIN,40.0,210.82,108.862080,None,USA,1995,1,...,3.2,3.9,1.6,6.6,0.031,0.262,0.117,0.491,0.164,2015-16

In [111]:
data[(data["age"]>=20)&(data["age"]<25)][["player_name","team_abbreviation","age"]].sort_values(by="age",ascending=False)

                    player_name team_abbreviation   age
3                   Ed O'Bannon               DAL  24.0
8058                 Jan Vesely               DEN  24.0
3797                 Brian Cook               LAL  24.0
3793           Curtis Borchardt               UTA  24.0
3791                  DJ Mbenga               DAL  24.0
...                         ...               ...   ...
10731                 Ja Morant               MEM  20.0
4440             Ersan Ilyasova               MIL  20.0
3986   Martynas Andriuskevicius               CLE  20.0
3985            Marvin Williams               ATL  20.0
5794           Anthony Randolph               GSW  20.0

[3531 rows x 3 columns]

In [115]:
data[data["player_name"]=="Kevin Garnett"][["team_abbreviation","season"]]

     team_abbreviation   season
337                MIN  1996-97
543                MIN  1997-98
1094               MIN  1998-99
1698               MIN  1999-00
2084               MIN  2000-01
2254               MIN  2001-02
3007               MIN  2002-03
3134               MIN  2003-04
3578               MIN  2004-05
4032               MIN  2005-06
4817               MIN  2006-07
5163               BOS  2007-08
5412               BOS  2008-09
6164               BOS  2009-10
6246               BOS  2010-11
7025               BOS  2011-12
7458               BOS  2012-13
7973               BKN  2013-14
8339               MIN  2014-15
8793               MIN  2015-16

In [114]:
data.columns

Index(['Unnamed: 0', 'player_name', 'team_abbreviation', 'age',
       'player_height', 'player_weight', 'college', 'country', 'draft_year',
       'draft_round', 'draft_number', 'gp', 'pts', 'reb', 'ast', 'net_rating',
       'oreb_pct', 'dreb_pct', 'usg_pct', 'ts_pct', 'ast_pct', 'season'],
      dtype='object')

In [120]:
data.groupby("team_abbreviation")["age"].mean()

team_abbreviation
ATL    26.903394
BKN    26.700000
BOS    26.651226
CHA    26.299213
CHH    29.056180
CHI    26.810298
CLE    26.953846
DAL    28.250000
DEN    26.569892
DET    27.497207
GSW    26.789894
HOU    27.984127
IND    27.126685
LAC    27.341902
LAL    27.309973
MEM    26.403175
MIA    28.410853
MIL    27.204852
MIN    26.904372
NJN    27.455253
NOH    27.356643
NOK    26.625000
NOP    26.581967
NYK    27.832884
OKC    26.133333
ORL    27.024457
PHI    26.457895
PHX    27.071823
POR    26.539510
SAC    26.784916
SAS    29.103448
SEA    27.395604
TOR    27.033333
UTA    27.008333
VAN    27.138889
WAS    26.910290
Name: age, dtype: float64

In [124]:
data.groupby("team_abbreviation").count()

,Unnamed: 0,player_name,age,player_height,player_weight,college,country,draft_year,draft_round,draft_number,...,pts,reb,ast,net_rating,oreb_pct,dreb_pct,usg_pct,ts_pct,ast_pct,season
team_abbreviation,,,,,,,,,,,,,,,,,,,,,
ATL,383,383,383,383,383,383,383,383,383,383,...,383,383,383,383,383,383,383,383,383,383
BKN,140,140,140,140,140,140,140,140,140,140,...,140,140,140,140,140,140,140,140,140,140
BOS,367,367,367,367,367,367,367,367,367,367,...,367,367,367,367,367,367,367,367,367,367
CHA,254,254,254,254,254,254,254,254,254,254,...,254,254,254,254,254,254,254,254,254,254
CHH,89,89,89,89,89,89,89,89,89,89,...,89,89,89,89,89,89,89,89,89,89
CHI,369,369,369,369,369,369,369,369,369,369,...,369,369,369,369,369,369,369,369,369,369
CLE,390,390,390,390,390,390,390,390,390,390,...,390,390,390,390,390,390,390,390,390,390
DAL,384,384,384,384,384,384,384,384,384,384,...,384,384,384,384,384,384,384,384,384,384
DEN,372,372,372,372,372,372,372,372,372,372,...,372,372,372,372,372,372,372,372,372,372
DET,358,358,358,358,358,358,358,358,358,358,...,358,358,358,358,358,358,358,358,358,358
GSW,376,376,376,376,376,376,376,376,376,376,...,376,376,376,376,376,376,376,376,376,376
HOU,378,378,378,378,378,378,378,378,378,378,...,378,378,378,378,378,378,378,378,378,378
IND,371,371,371,371,371,371,371,371,371,371,...,371,371,371,371,371,371,371,371,371,371
LAC,389,389,389,389,389,389,389,389,389,389,...,389,389,389,389,389,389,389,389,389,389
LAL,371,371,371,371,371,371,371,371,371,371,...,371,371,371,371,371,371,371,371,371,371
MEM,315,315,315,315,315,315,315,315,315,315,...,315,315,315,315,315,315,315,315,315,315
MIA,387,387,387,387,387,387,387,387,387,387,...,387,387,387,387,387,387,387,387,387,387
MIL,371,371,371,371,371,371,371,371,371,371,...,371,371,371,371,371,371,371,371,371,371
MIN,366,366,366,366,366,366,366,366,366,366,...,366,366,366,366,366,366,366,366,366,366
NJN,257,257,257,257,257,257,257,257,257,257,...,257,257,257,257,257,257,257,257,257,257
NOH,143,143,143,143,143,143,143,143,143,143,...,143,143,143,143,143,143,143,143,143,143
NOK,32,32,32,32,32,32,32,32,32,32,...,32,32,32,32,32,32,32,32,32,32
NOP,122,122,122,122,122,122,122,122,122,122,...,122,122,122,122,122,122,122,122,122,122
NYK,371,371,371,371,371,371,371,371,371,371,...,371,371,371,371,371,371,371,371,371,371
OKC,195,195,195,195,195,195,195,195,195,195,...,195,195,195,195,195,195,195,195,195,195
ORL,368,368,368,368,368,368,368,368,368,368,...,368,368,368,368,368,368,368,368,368,368
PHI,380,380,380,380,380,380,380,380,380,380,...,380,380,380,380,380,380,380,380,380,380
PHX,362,362,362,362,362,362,362,362,362,362,...,362,362,362,362,362,362,362,362,362,362
POR,367,367,367,367,367,367,367,367,367,367,...,367,367,367,367,367,367,367,367,367,367
SAC,358,358,358,358,358,358,358,358,358,358,...,358,358,358,358,358,358,358,358,358,358
SAS,377,377,377,377,377,377,377,377,377,377,...,377,377,377,377,377,377,377,377,377,377
SEA,182,182,182,182,182,182,182,182,182,182,...,182,182,182,182,182,182,182,182,182,182
TOR,390,390,390,390,390,390,390,390,390,390,...,390,390,390,390,390,390,390,390,390,390
UTA,360,360,360,360,360,360,360,360,360,360,...,360,360,360,360,360,360,360,360,360,360
VAN,72,72,72,72,72,72,72,72,72,72,...,72,72,72,72,72,72,72,72,72,72
WAS,379,379,379,379,379,379,379,379,379,379,...,379,379,379,379,379,379,379,379,379,379

In [122]:
data.groupby("team_abbreviation")["player_name"].count()

team_abbreviation
ATL    383
BKN    140
BOS    367
CHA    254
CHH     89
CHI    369
CLE    390
DAL    384
DEN    372
DET    358
GSW    376
HOU    378
IND    371
LAC    389
LAL    371
MEM    315
MIA    387
MIL    371
MIN    366
NJN    257
NOH    143
NOK     32
NOP    122
NYK    371
OKC    195
ORL    368
PHI    380
PHX    362
POR    367
SAC    358
SAS    377
SEA    182
TOR    390
UTA    360
VAN     72
WAS    379
Name: player_name, dtype: int64

In [126]:
data["team_abbreviation"].nunique()

36

In [128]:
data["team_abbreviation"].value_counts(ascending=False)

CLE    390
TOR    390
LAC    389
MIA    387
DAL    384
ATL    383
PHI    380
WAS    379
HOU    378
SAS    377
GSW    376
DEN    372
LAL    371
NYK    371
IND    371
MIL    371
CHI    369
ORL    368
BOS    367
POR    367
MIN    366
PHX    362
UTA    360
SAC    358
DET    358
MEM    315
NJN    257
CHA    254
OKC    195
SEA    182
NOH    143
BKN    140
NOP    122
CHH     89
VAN     72
NOK     32
Name: team_abbreviation, dtype: int64

In [133]:
data[data["player_name"].str.contains("LeBron")]

,Unnamed: 0,player_name,team_abbreviation,age,player_height,player_weight,college,country,draft_year,draft_round,...,pts,reb,ast,net_rating,oreb_pct,dreb_pct,usg_pct,ts_pct,ast_pct,season
3120,3120,LeBron James,CLE,19.0,203.20,108.86208,None,USA,2003,1,...,20.9,5.5,5.9,-2.6,0.035,0.117,0.280,0.488,0.268,2003-04
3617,3617,LeBron James,CLE,20.0,203.20,108.86208,None,USA,2003,1,...,27.2,7.4,7.2,1.9,0.038,0.170,0.297,0.554,0.324,2004-05
4075,4075,LeBron James,CLE,21.0,203.20,108.86208,None,USA,2003,1,...,31.4,7.0,6.6,4.2,0.026,0.171,0.336,0.568,0.315,2005-06
4778,4778,LeBron James,CLE,22.0,203.20,108.86208,None,USA,2003,1,...,27.3,6.7,6.0,5.4,0.029,0.166,0.309,0.552,0.281,2006-07
5104,5104,LeBron James,CLE,23.0,203.20,113.39800,None,USA,2003,1,...,30.0,7.9,7.2,2.4,0.049,0.178,0.333,0.568,0.352,2007-08
5430,5430,LeBron James,CLE,24.0,203.20,113.39800,None,USA,2003,1,...,28.4,7.6,7.2,14.7,0.042,0.189,0.334,0.591,0.365,2008-09
6127,6127,LeBron James,CLE,25.0,203.20,113.39800,None,USA,2003,1,...,29.7,7.3,8.6,10.8,0.030,0.185,0.333,0.604,0.398,2009-10
6266,6266,LeBron James,MIA,26.0,203.20,113.39800,None,USA,2003,1,...,26.7,7.5,7.0,10.5,0.033,0.184,0.312,0.594,0.343,2010-11
7004,7004,LeBron James,MIA,27.0,203.20,113.39800,None,USA,2003,1,...,27.1,7.9,6.2,10.7,0.050,0.196,0.317,0.605,0.318,2011-12
7428,7428,LeBron James,MIA,28.0,203.20,113.39800,None,USA,2003,1,...,26.8,8.0,7.3,14.1,0.044,0.208,0.298,0.640,0.344,2012-13
7954,7954,LeBron James,MIA,29.0,203.20,113.39800,None,USA,2003,1,...,27.1,6.9,6.3,7.9,0.037,0.188,0.309,0.649,0.311,2013-14
8322,8322,LeBron James,CLE,30.0,203.20,113.39800,None,USA,2003,1,...,25.3,6.0,7.4,9.8,0.025,0.166,0.324,0.577,0.366,2014-15
8640,8640,LeBron James,CLE,31.0,203.20,113.39800,None,USA,2003,1,...,25.3,7.4,6.8,11.0,0.047,0.187,0.311,0.588,0.339,2015-16
9220,9220,LeBron James,CLE,32.0,203.20,113.39800,None,USA,2003,1,...,26.4,8.6,8.7,7.7,0.040,0.209,0.297,0.619,0.388,2016-17
10028,10028,LeBron James,CLE,33.0,203.20,113.39800,None,USA,2003,1,...,27.5,8.6,9.1,1.6,0.033,0.201,0.310,0.621,0.432,2017-18
10520,10520,LeBron James,LAL,34.0,203.20,113.39800,None,USA,2003,1,...,27.4,8.5,8.3,2.0,0.029,0.193,0.311,0.588,0.376,2018-19
11042,11042,LeBron James,LAL,35.0,205.74,113.39800,None,USA,2003,1,...,25.6,7.8,10.7,10.4,0.028,0.186,0.308,0.581,0.480,2019-20